# Generated by Django 6.1.1 on 2026-09-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='freight_type',
            field=models.CharField(choices=[('land', 'Land Freight'), ('air', 'Air Freight'), ('sea', 'Sea Freight')], default='land', max_length=10),
        ),
    ]
