# Generated by Django 6.1.1 on 2026-09-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_freight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
